### PR TITLE
Improves SkCanvasService registration to handle incorrect unit initialization order

### PR DESCRIPTION
**Pull request by alyssonrpg**
This PR improves SkCanvasService registration to handle incorrect unit initialization order.

It was not possible to correctly register Skia4Delphi canvas service for Android with Delphi Alexandria 11.1 in a "real-world" project with lots of complex unit dependencies. I tried many "uses order" to achieve the correct initialization but failed.

Changes:
- A new class named `TSkCanvasServiceRegistrator` was created with a public static method `TryRegister` that can be optionally called from the project's main code before `Application.Initialize` call.
- A attempt to register SkCanvasService is made from the "Skia.FMX.Graphics" initialization, but if it detects incorrect initialization order, it schedules a new attempt of registration using `TThread.ForceQueue`. This solves the issue for Android without the optional step described previously.

### CODE REVIEW

**Comment by viniciusfbb** [comment]
Hi @alyssonrpg, thanks so much for the pull request.

First, a brief explanation of how it works:
The CanvasService is registered at initialization of FMX.Platforms, which is declared in the uses of Skia.FMX.Graphics, so there is no way that the FMX original CanvasService is not registered at the time that the Skia CanvasService is registered.

After registering Skia's CanvasService, we wait for the FMX system to call TSkCanvasService.RegisterCanvasClasses, to then check if the GlobalUseSkia variable is True or False (after all, the rendering system is an optional feature), to define whether it will register the canvas / textlayout based on Skia or the default from FMX.

Here's an important note: FMX will only call TSkCanvasService.RegisterCanvasClasses (to check GlobalUseSkia and register the canvas/textlayout classes) the first time a form is created, or when a TBitmap or a TTextLayout is created. In general, we advise that your project's .dpr have the following order:

```delphi
uses
  System.StartUpCopy,
  FMX.Forms,
  FMX.Types,
  Skia.FMX,
  ...

begin
   GlobalUseSkia := True;
   ...
```

However, this can fail, because the TSkCanvasService.RegisterCanvasClasses can be called before the begin of dpr, that is, before setting `GlobalUseSkia := True;`, when it is still False, which will make the TSkCanvasService.RegisterCanvasClasses register the original FMX Canvas/TextLayout and not the Skia one. This is caused by what I said earlier, i.e. if a TBitmap or TTextLayout is created before `GlobalUseSkia := True;`, Skia's rendering system (Canvas/TextLayout) is not registered.

But what code is executed before the .dpr begin? All code that is in the initialization or class constructors of units used by dpr (including other units used in these units, i.e. even the initialization of other libraries). And if any TBitmap or TTextLayout or TForm is being created in one of these initializations, the canvas system is initialized before setting `GlobalUseSkia := True;`.

The solution for this is not to change the initialization / class constructor of the units, but to create a unit that executes `GlobalUseSkia := True;` before performing the initializations of the other units. So in your project, you will create a unit called `Project.StartUp.pas`, and your .dpr need to be:

```delphi
uses
   System.StartUpCopy,
   FMX.Types,
   FMX.Forms,
   Project.StartUp in 'Project.StartUp.pas',
   ...
```

In which the `Project.StartUp.pas` will have the following code:

```delphi
unit Project.StartUp;

interface

implementation

uses
   { Delphi }
   FMX.Types
   {$IFDEF SKIA}
   { Third party },
   Skia.FMX
   {$ENDIF};

initialization
   GlobalUseMetal := True;
   {$IFDEF SKIA} // When you enable the Skia in your project menu, this define will be automatically true
   GlobalUseSkia := True;
   {$ENDIF}
end.
```

So having created a GlobalUseSkia variable instead of a define is wrong? Maybe it's not the best option, but we follow the FMX pattern, since it has the GlobalUseMetal variable to activate rendering using Metal, among other rendering variables, which even face the same problem.

**Comment by alyssonrpg** [comment]
All orientations to use SkCanvas as the default canvas class were used (setting GlobalUseSkia to true and referencing the Skia4Delphi units after FMX.Forms).

It works fine when targeting Win64/Win32, while targeting Android64 sometimes fails.

*******
Reason for the failure: The `Sia.FMX.Graphics.pas` initialization is being called before `FMX.Platforms.pas` initialization but it should be the inverse. I suspect this is happening because of the different toolchain used to compile and link for android.
*******

It should be called after `FMX.Platforms` initialization, but sometimes, according to the project, it does not happen. I tried some approaches to get the expected initialization order, but it was more and more resembling a "gambiarra" solution.

This PR does not change the `GlobalUseSkia` pattern but handles that case where the unit's initialization is called in "wrong order" and allows a more deterministic registration of the TSkCanvasService

**Comment by alyssonrpg** [comment]
If you want, I can record a video showing how sometimes the unit's initialization s called in such a non-deterministic order while targeting Android64.

In the same project, using all the orientations, sometimes the dependency tree of the units causes the `Sia.FMX.Graphics` initialization to be called before `FMX.Platform` initialization.

> All orientations to use SkCanvas as the default canvas class were used (setting GlobalUseSkia to true and referencing the Skia4Delphi units after FMX.Forms).
> 
> It works fine when targeting Win64/Win32, while targeting Android64 sometimes fails.
> 
> Reason for the failure: The `Sia.FMX.Graphics.pas` initialization is being called before `FMX.Platforms.pas` initialization but it should be the inverse. I suspect this is happening because of the different toolchain used to compile and link for android.
> 
> It should be called after `FMX.Platforms` initialization, but sometimes, according to the project, it does not happen. I tried some approaches to get the expected initialization order, but it was more and more resembling a "gambiarra" solution.
> 
> This PR does not change the `GlobalUseSkia` pattern but handles that case where the unit's initialization is called in "wrong order" and allows a more deterministic registration of the TSkCanvasService

**Comment by viniciusfbb** [comment]
@alyssonrpg, thank you very much for the clarification. Unit initialization is always called from the main thread internally and the order must be the same on any platform, otherwise it is a compiler issue and needs to be reported urgently. What's weird about this is when you say this happens "sometimes", which would perhaps rule out a compiler issue.

I'll try to simulate the problem on my devices.

**Comment by viniciusfbb** [comment]
> In the same project, using all the orientations, sometimes the dependency tree of the units causes the Skia.FMX.Graphics initialization to be called before FMX.Platform initialization.

And if you change the FMX.Platform inside the Skia.FMX.Graphics.pas, from implementation uses to interface uses, it solve the problem?

**Comment by alyssonrpg** [comment]
> > In the same project, using all the orientations, sometimes the dependency tree of the units causes the Skia.FMX.Graphics initialization to be called before FMX.Platform initialization.
> 
> And if you change the FMX.Platform inside the Skia.FMX.Graphics.pas, from implementation uses to interface uses, it solve the problem?

One of the attempts I tried to make was this one suggested, and it didn't work.

I have a unit that references the Skia4Delphi units. When it is compiled, the initialization order error occurs (It is referred to as one of the last units in the project). If I stop compiling it, initialization happens in the expected order 🤷.

**Comment by viniciusfbb** [comment]
> I have a unit that references the Skia4Delphi units. When it is compiled, the initialization order error occurs. This "magic" unit is referenced as one of the last units in the project. If I stop compiling it, the initialization happens in the expected order 🤷.

Right, but your .dpr uses starts with this?

```delphi
uses
  System.StartUpCopy,
  FMX.Forms,
  FMX.Types,
  Skia.FMX,
  ...
```

**Comment by alyssonrpg** [comment]
> > I have a unit that references the Skia4Delphi units. When it is compiled, the initialization order error occurs. This "magic" unit is referenced as one of the last units in the project. If I stop compiling it, the initialization happens in the expected order 🤷.
> 
> Right, but your .dpr uses starts with this?
> 
> ```pascal
> uses
>   System.StartUpCopy,
>   FMX.Forms,
>   FMX.Types,
>   Skia.FMX,
>   ...
> ```

Not exactly the same because of other project needs, but the core idea is there: Those units of FMX before Skia.

**Comment by alyssonrpg** [comment]
> > I have a unit that references the Skia4Delphi units. When it is compiled, the initialization order error occurs. This "magic" unit is referenced as one of the last units in the project. If I stop compiling it, the initialization happens in the expected order 🤷.
> 
> Right, but your .dpr uses starts with this?
> 
> ```pascal
> uses
>   System.StartUpCopy,
>   FMX.Forms,
>   FMX.Types,
>   Skia.FMX,
>   ...
> ```

@viniciusfbb I did a test by changing the order of units to start exactly the same as the example you gave, but the boot order issue still occurred.

Maybe we can come up with a different solution, but I don't think we can assume that initialization of `Skia.FMX.Graphics` will always happen after the initialization of `FMX.Platform`.

image

**Comment by viniciusfbb** [comment]
Ok, I will made some tests too

**Comment by alyssonrpg** [comment]
@viniciusfbb, I did some digging and discovered a patched Delphi file in my build chain that caused a circular reference. 

A custom textlayout implementation to replace the built-in textlayout. I am adding skia backend to the custom textlayout and this caused a circular reference due the way the replacement textlayout was being "registered". 

Changed some units referencing and the initialization order came back to the expected one. 

I will keep the PR changes to my fork, as it handles the out of order initialization issue and could previne future struggle, but it may not be needed for others. Perhaps may need, I don't know.

**Comment by viniciusfbb** [comment]
@alyssonrpg Excellent! I was worried about this issue.

Unfortunately the ForceQueue worries me as it will almost always dump the record after the CanvasService is initialized. Even if you manage to avoid the "Item not found" exception, it will not be able to fulfill its purpose of registering skia's canvas/textlayout.

Some exceptions, mainly due to programming errors, do not have to be avoided. It's like putting a
```delphi
try
...
except
end
```
in a faulty code.

Anyway, I appreciate all the effort to try to improve the lib. We need more contributions from the community.

Remembering that the most correct way to initialize `GlobalUseSkia := True;` is the way I told you above, creating a Project.Startup.pas.

**Pull request closed without merging**
